import React, {useState, useEffect, useRef} from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useInView, AnimatePresence } from 'framer-motion';
import { ArrowUpRight, Play, Menu, ArrowRight, Check, Plus, MoveUpRight, Sun, Moon, Languages } from 'lucide-react';
import './styles.css';

const fade = { hidden:{opacity:0,y:28}, visible:{opacity:1,y:0,transition:{duration:.85,ease:[.16,1,.3,1]}} };
function Reveal({children, className=''}){const ref=useRef(null);const is=useInView(ref,{once:true,amount:.15});return <motion.div ref={ref} className={className} variants={fade} initial="hidden" animate={is?'visible':'hidden'}>{children}</motion.div>}
function Button({children, secondary=false, className=''}){return <button className={`button ${secondary?'button-ghost':''} ${className}`}>{children}<ArrowUpRight size={16}/></button>}
function Chart({large=false}){return <div className={`chart ${large?'chart-large':''}`}><div className="chart-labels"><span>112.68</span><span>108.51</span><span>104.34</span><span>100.17</span></div><div className="grid-lines"/><svg viewBox="0 0 800 300" preserveAspectRatio="none" aria-label="Ascending market chart"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#cdb7ff" stopOpacity=".28"/><stop offset="100%" stopColor="#cdb7ff" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d="M0 253 C42 230 52 245 88 220 S125 250 155 210 S205 235 238 183 S278 210 312 160 S365 183 395 133 S437 172 472 115 S516 133 554 91 S598 119 627 65 S672 100 705 55 S754 75 800 15 L800 300 L0 300Z"/><path className="chart-line" d="M0 253 C42 230 52 245 88 220 S125 250 155 210 S205 235 238 183 S278 210 312 160 S365 183 395 133 S437 172 472 115 S516 133 554 91 S598 119 627 65 S672 100 705 55 S754 75 800 15"/></svg><div className="live-chip"><i/> LIVE • BTC/USD <b>+12.84%</b></div>{large&&<div className="chart-bottom"><span>08:00</span><span>10:00</span><span>12:00</span><span>14:00</span><span>16:00</span></div>}</div>}
function Stat({number,label,suffix=''}){const [v,setV]=useState(0);const ref=useRef();const seen=useInView(ref,{once:true});useEffect(()=>{if(!seen)return;let start;const end=Number(number);const tick=t=>{if(!start)start=t;const p=Math.min((t-start)/1500,1);setV(Math.floor(end*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)},[seen,number]);return <div ref={ref} className="stat"><strong>{v.toLocaleString()}{suffix}</strong><span>{label}</span></div>}
const benefits=[['01','PROVEN SYSTEMS','Institutional-grade frameworks that help you read the market before it moves.'],['02','RISK FIRST','Build capital with discipline. Our framework is engineered to protect downside.'],['03','LIFETIME ACCESS','Markets evolve. Your access and every future update stays with you.'],['04','PRIVATE CIRCLE','A focused community for people who take their craft seriously.']];
const modules=['Market Foundations','Technical Analysis','Price Action Mastery','Risk Architecture','Trader Psychology','Scaling Capital'];
const faqs=[['Is this course for beginners?','Yes. We start with the core mechanics, then progress through institutional-level execution. The system is designed to create clarity at every stage.'],['How much time should I commit?','The program is self-paced. Most members devote 4–6 focused hours a week and complete the foundations in six weeks.'],['What markets does it cover?','Our principles apply to crypto, forex, indices, and equities. We demonstrate the framework on liquid, global markets.'],['Do I get lifetime access?','Yes. One enrollment gives you permanent access to every module, future updates, and the private member space.']];
const ruText={
 '01 — THE STANDARD':'01 — НАШ СТАНДАРТ','LESS NOISE.':'МЕНЬШЕ ШУМА.','MORE':'БОЛЬШЕ','PRECISION.':'ТОЧНОСТИ.',
 'Most courses sell information. We build a decision-making system — distilled from years of market experience, designed for your next level.':'Большинство курсов продают информацию. Мы создаём систему принятия решений, основанную на многолетнем опыте рынка и созданную для вашего следующего уровня.',
 'Discover our method':'Узнать о методе','02 — WHAT SETS US APART':'02 — ЧТО НАС ОТЛИЧАЕТ','( THE RØW STANDARD )':'( СТАНДАРТ RØW )',
 'PROVEN SYSTEMS':'ПРОВЕРЕННЫЕ СИСТЕМЫ','Institutional-grade frameworks that help you read the market before it moves.':'Институциональные методики, которые помогают читать рынок до его движения.',
 'RISK FIRST':'РИСК ПРЕЖДЕ ВСЕГО','Build capital with discipline. Our framework is engineered to protect downside.':'Создавайте капитал дисциплинированно. Наша система построена для защиты от потерь.',
 'LIFETIME ACCESS':'ДОСТУП НАВСЕГДА','Markets evolve. Your access and every future update stays with you.':'Рынки меняются. Ваш доступ и все будущие обновления остаются с вами.',
 'PRIVATE CIRCLE':'ЗАКРЫТОЕ СООБЩЕСТВО','A focused community for people who take their craft seriously.':'Сообщество для людей, которые серьёзно относятся к своему делу.',
 '03 — INSIDE THE COURSE':'03 — ВНУТРИ КУРСА','BUILD YOUR':'СОЗДАЙТЕ','EDGE.':'ПРЕИМУЩЕСТВО.',
 'From first principles to high-conviction execution, every lesson is a focused step toward a sharper trading identity.':'От основ до уверенного исполнения: каждый урок — точный шаг к более сильной торговой системе.',
 'Explore curriculum':'Смотреть программу','04 — THE PROOF':'04 — РЕЗУЛЬТАТЫ','NUMBERS THAT':'ЦИФРЫ, КОТОРЫЕ','SPEAK':'ГОВОРЯТ','LOUDER.':'САМИ.',
 'Members worldwide':'Участников по всему миру','Positive reviews':'Положительных отзывов','Member profit':'Прибыль участников','*Based on voluntarily reported results from active RØW members.':'*На основе добровольно предоставленных результатов активных участников RØW.',
 '05 — THE CURRICULUM':'05 — ПРОГРАММА','SIX PARTS.':'ШЕСТЬ МОДУЛЕЙ.','ONE':'ОДНА','TRANSFORMATION.':'ТРАНСФОРМАЦИЯ.',
 'Market Foundations':'Основы рынка','Technical Analysis':'Технический анализ','Price Action Mastery':'Мастерство Price Action','Risk Architecture':'Архитектура риска','Trader Psychology':'Психология трейдера','Scaling Capital':'Масштабирование капитала',
 'Learn the language of liquidity, structure, and market mechanics.':'Освойте язык ликвидности, структуры и механики рынка.','A focused system to turn market information into deliberate action.':'Сфокусированная система, превращающая информацию рынка в осознанные действия.',
 'RØW stripped away everything I thought I knew about trading. The system gave me the one thing I was missing:':'RØW убрал всё лишнее из моих представлений о трейдинге. Система дала мне то, чего не хватало:','clarity.':'ясность.','MEMBER SINCE 2024':'УЧАСТНИК С 2024',
 '06 — QUESTIONS, ANSWERED':'06 — ОТВЕТЫ НА ВОПРОСЫ','NO':'НИКАКОГО','STATIC.':'ШУМА.','JUST CLARITY.':'ТОЛЬКО ЯСНОСТЬ.',
 'Is this course for beginners?':'Подходит ли курс новичкам?','Yes. We start with the core mechanics, then progress through institutional-level execution. The system is designed to create clarity at every stage.':'Да. Мы начинаем с ключевой механики, затем переходим к исполнению институционального уровня. Система создаёт ясность на каждом этапе.',
 'How much time should I commit?':'Сколько времени потребуется?','The program is self-paced. Most members devote 4–6 focused hours a week and complete the foundations in six weeks.':'Программа проходит в вашем темпе. Большинство участников уделяет 4–6 часов в неделю и проходит базу за шесть недель.',
 'What markets does it cover?':'Какие рынки рассматриваются?','Our principles apply to crypto, forex, indices, and equities. We demonstrate the framework on liquid, global markets.':'Наши принципы применимы к крипто, Forex, индексам и акциям. Мы показываем систему на ликвидных глобальных рынках.',
 'Do I get lifetime access?':'Доступ остаётся навсегда?','Yes. One enrollment gives you permanent access to every module, future updates, and the private member space.':'Да. Одно участие даёт постоянный доступ ко всем модулям, будущим обновлениям и закрытому пространству участников.',
 'THE NEXT MOVE IS YOURS':'СЛЕДУЮЩИЙ ШАГ ЗА ВАМИ','YOUR FUTURE':'ВАШЕ БУДУЩЕЕ','STARTS':'НАЧИНАЕТСЯ','TODAY.':'СЕГОДНЯ.','Start your evolution':'НАЧАТЬ ПУТЬ','Lifetime access':'Доступ навсегда','30-day guarantee':'Гарантия 30 дней','BUILT FOR THE DISCIPLINED':'СОЗДАНО ДЛЯ ДИСЦИПЛИНИРОВАННЫХ'
};
function App(){const [open,setOpen]=useState(null);const [light,setLight]=useState(false);const [russian,setRussian]=useState(false);const t=(en,ru)=>russian?ru:en;const c={method:t('Method','Метод'),program:t('Program','Программа'),outcomes:t('Outcomes','Результаты'),apply:t('Apply now','Принять участие'),start:t('Start now','Начать'),preview:t('Watch preview','Смотреть превью'),heroTop:t('PRIVATE TRADING EDUCATION · 2026','ЧАСТНОЕ ОБУЧЕНИЕ ТРЕЙДИНГУ · 2026'),heroA:t('THE BEST','ЛУЧШИЙ'),heroB:t('TRADING COURSE','КУРС ПО ТРЕЙДИНГУ'),heroC:t('OF 2026','2026 ГОДА'),heroText:t('Learn the discipline, clarity, and edge to build real trading skill — and earn your first million.','Освойте дисциплину, ясность и преимущество, чтобы развить реальные навыки трейдинга и заработать свой первый миллион.'),scroll:t('SCROLL TO EXPLORE','ЛИСТАЙТЕ, ЧТОБЫ УЗНАТЬ БОЛЬШЕ')};return <main className={`${light?'light-theme':''} ${russian?'lang-ru':''}`}><nav><a className="brand" href="#">RØW<br/><em>CAPITAL</em></a><div className="navlinks"><a href="#method">{c.method}</a><a href="#program">{c.program}</a><a href="#outcomes">{c.outcomes}</a></div><div className="nav-actions"><button className="icon-button" onClick={()=>setLight(!light)} aria-label="Theme">{light?<Moon size={15}/>:<Sun size={15}/>}<span>{light?'DARK':'LIGHT'}</span></button><button className="icon-button language-button" onClick={()=>setRussian(!russian)} aria-label="Language"><Languages size={15}/><span>{russian?'RU':'EN'}</span></button><Button className="nav-button">{c.apply}</Button></div><Menu className="mobile-menu" aria-label="Navigation"/></nav>
<section className="hero"><div className="hero-orb"/><div className="hero-graphic"><Chart large/></div><div className="hero-copy"><motion.p initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.2}} className="eyebrow"><span/> {c.heroTop}</motion.p><motion.h1 initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:1}}><span>{c.heroA}</span><br/>{c.heroB}<br/><i>{c.heroC}</i></motion.h1><motion.div className="hero-bottom" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1}}><p>{c.heroText}</p><div><Button>{c.start}</Button><Button secondary><Play size={14} fill="currentColor"/> {c.preview}</Button></div></motion.div></div><div className="scroll-note">{c.scroll} <span/></div></section>
<section className="intro" id="method"><Reveal><p className="eyebrow">01 — THE STANDARD</p><h2>LESS NOISE.<br/><span>MORE</span> <i>PRECISION.</i></h2></Reveal><Reveal className="intro-side"><p>Most courses sell information. We build a decision-making system — distilled from years of market experience, designed for your next level.</p><a href="#program" className="text-link">Discover our method <ArrowRight size={17}/></a></Reveal></section>
<section className="benefits"><div className="benefit-head"><p className="eyebrow">02 — WHAT SETS US APART</p><span>( THE RØW STANDARD )</span></div><div className="benefit-grid">{benefits.map((b,i)=><Reveal key={b[0]}><article className="benefit-card"><small>{b[0]}</small><div className="plus">+</div><h3>{b[1]}</h3><p>{b[2]}</p><div className="card-line"/></article></Reveal>)}</div></section>
<section className="dashboard"><Reveal className="dash-copy"><p className="eyebrow">03 — INSIDE THE COURSE</p><h2>BUILD YOUR<br/><i>EDGE.</i></h2><p>From first principles to high-conviction execution, every lesson is a focused step toward a sharper trading identity.</p><Button secondary>Explore curriculum</Button></Reveal><Reveal className="terminal"><div className="terminal-top"><span>RØW TERMINAL</span><span>12:48:06 UTC <i/></span></div><div className="terminal-price"><div><small>BTC / USD</small><b>$104,827.20</b><em>+ 2.84%</em></div><div className="terminal-tabs"><span className="active">1H</span><span>4H</span><span>1D</span></div></div><Chart/><div className="terminal-foot"><span>Open interest <b>$54.19B</b></span><span>Volume <b>$29.87B</b></span><span>Funding <b className="purple">0.0121%</b></span></div></Reveal></section>
<section className="outcomes" id="outcomes"><Reveal><p className="eyebrow">04 — THE PROOF</p><h2>NUMBERS THAT<br/>SPEAK <i>LOUDER.</i></h2></Reveal><div className="stats"> <Stat number="10000" suffix="+" label="Members worldwide"/><Stat number="95" suffix="%" label="Positive reviews"/><Stat number="15" suffix="M+" label="Member profit"/></div><p className="outcome-caption">*Based on voluntarily reported results from active RØW members.</p></section>
<section className="program" id="program"><Reveal><div className="program-title"><p className="eyebrow">05 — THE CURRICULUM</p><h2>SIX PARTS.<br/><i>ONE</i> TRANSFORMATION.</h2></div></Reveal><div className="module-list">{modules.map((m,i)=><Reveal key={m}><div className="module"><span>0{i+1}</span><h3>{m}</h3><p>{i===0?'Learn the language of liquidity, structure, and market mechanics.':'A focused system to turn market information into deliberate action.'}</p><MoveUpRight size={20}/></div></Reveal>)}</div></section>
<section className="quote"><Reveal><span className="quote-mark">“</span><blockquote>RØW stripped away everything I thought I knew about trading. The system gave me the one thing I was missing: <i>clarity.</i></blockquote><div className="person"><div>JL</div><p>JAMES LEE<br/><span>MEMBER SINCE 2024</span></p></div></Reveal></section>
<section className="faq"><Reveal><p className="eyebrow">06 — QUESTIONS, ANSWERED</p><h2>NO <i>STATIC.</i><br/>JUST CLARITY.</h2></Reveal><div className="faq-list">{faqs.map((f,i)=><div className="faq-item" key={f[0]} onClick={()=>setOpen(open===i?null:i)}><div><span>0{i+1}</span><h3>{f[0]}</h3><motion.button animate={{rotate:open===i?45:0}}><Plus/></motion.button></div><AnimatePresence>{open===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{f[1]}</motion.p>}</AnimatePresence></div>)}</div></section>
<section className="final"><div className="final-glow"/><Reveal><p className="eyebrow">THE NEXT MOVE IS YOURS</p><h2>YOUR FUTURE<br/>STARTS <i>TODAY.</i></h2><Button>Start your evolution</Button><p className="fineprint"><Check size={13}/> Lifetime access <Check size={13}/> 30-day guarantee</p></Reveal><footer><span>© 2026 RØW CAPITAL</span><span>BUILT FOR THE DISCIPLINED</span><span>INSTAGRAM &nbsp; X / TWITTER</span></footer></section></main>}
function AccountPage(){const [done,setDone]=useState(false);return <main className="account-page"><nav><a className="brand" href="#">RØW<br/><em>CAPITAL</em></a><button className="back-button" onClick={()=>{location.hash=''}}>← ВЕРНУТЬСЯ НА ГЛАВНУЮ</button></nav><section className="account-shell"><p className="eyebrow"><span/> PRIVATE MEMBER ACCESS</p><h1>СОЗДАЙТЕ<br/><i>ЛИЧНЫЙ КАБИНЕТ.</i></h1><p className="account-lead">Ваш доступ к программе, материалам и закрытому сообществу RØW начинается здесь.</p>{done?<div className="success-card"><Check size={24}/><h2>ЗАЯВКА<br/><i>ПРИНЯТА.</i></h2><p>Мы отправили подтверждение на указанную электронную почту.</p></div>:<form className="signup-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><label>ФИО<input required placeholder="Иван Иванов"/></label><label>ЭЛЕКТРОННАЯ ПОЧТА<input required type="email" placeholder="you@example.com"/></label><label>НОМЕР ТЕЛЕФОНА<input required type="tel" placeholder="+7 (000) 000-00-00"/></label><label>ЮЗЕРНЕЙМ TELEGRAM<input required placeholder="@username"/></label><button className="button signup-button" type="submit">Создать аккаунт <ArrowUpRight size={16}/></button><p className="form-note">Продолжая, вы соглашаетесь с правилами платформы и политикой конфиденциальности.</p></form>}</section></main>}
function RouteApp(){const [signup,setSignup]=useState(location.hash==='#signup');useEffect(()=>{const sync=()=>setSignup(location.hash==='#signup');const go=e=>{const label=e.target.closest('button')?.textContent?.toLowerCase()||'';if(/начать|принять участие|start now|apply now|start your evolution/.test(label)){e.preventDefault();location.hash='signup'}};addEventListener('hashchange',sync);document.addEventListener('click',go);return()=>{removeEventListener('hashchange',sync);document.removeEventListener('click',go)}},[]);return signup?<AccountPage/>:<App/>}
createRoot(document.getElementById('root')).render(<RouteApp/>);
const originals=new Map();document.addEventListener('click',e=>{if(!e.target.closest('.language-button'))return;setTimeout(()=>{const isRu=document.querySelector('main').classList.contains('lang-ru');const w=document.createTreeWalker(document.querySelector('main'),NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{if(!originals.has(n))originals.set(n,n.nodeValue);const en=originals.get(n),key=en.trim(),ru=ruText[key];n.nodeValue=isRu&&ru?en.replace(key,ru):en})},0)});
